### ISSUE TITLE
Unsupported operation in getEncoded() for messages type 17,21,24

### ISSUE THREAD

**Issue by bushaev** [dma-ais/AisLib#35]
I'm trying to serialize AisMessages to Json using jackson, unfortunately it tries to serialize getEncoded(), which throws UnsupportedOperationException(). Is there a particular reason for this ?

**Comment by tbsalling** [comment]
No, not really. You could say, that `getEncoded` is poorly named, because it is not really a bean property.

I see three possible solutions:
1) Rename `getEncoded` to something else (which breaks compatibility)
2) Add `@JsonIgnore` to the method (which adds an extra dependency)
3) Write a custom Json serializer for AISMessage.

Given the disadvantages of 1) and 2) I tend to prefer option 3).

If you see other solutions you are welcome to bring them to the table or to submit a pull request.

**Comment by bushaev** [comment]
Implement getEncoded() for these messages ? Or i'm not seeing something ?

**Comment by tbsalling** [comment]
Ah yes - of course. That would also work - even though `getEncoded` in my opinion still really isn't a bean property.

If you can supply a pull request for this , then I'll review and merge it. You'll probably need a close look in the [ITU spec](http://www.itu.int/rec/R-REC-M.1371-5-201402-I) (Annex 8) to succeed.
